  FROM ruby:3.1.2
  ENV RAILS_ENV development
  ENV RAILS_SERVE_STATIC_FILES true
  ENV RAILS_LOG_TO_STDOUT true
  RUN apt-get update && apt-get install -y vim libpq-dev
  WORKDIR /app
  COPY Gemfile* .
  RUN bundle install  --without development test
  COPY . .
  EXPOSE 3000

  COPY entrypoint.sh /usr/local/bin/
  RUN chmod +x /usr/local/bin/entrypoint.sh

  ENTRYPOINT ["entrypoint.sh"]
  CMD ["rails", "server", "-b", "0.0.0.0"]
